name: sg-setup
on:
  push:
    paths:
      - 'dev/sg/dependencies/**.go'
      - 'dev/sg/internal/check/**.go'
jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test dependencies
        run: go test -v ./dev/sg/dependencies/... -sg-setup
